type Country = {
    name: { fr: string, en: string, ar: string };
    code: string;
};

export const countries: Country[] = [
  { name: { fr: 'Afghanistan', en: 'Afghanistan', ar: 'أفغانستان' }, code: 'AF' },
  { name: { fr: 'Afrique du Sud', en: 'South Africa', ar: 'جنوب أفريقيا' }, code: 'ZA' },
  { name: { fr: 'Albanie', en: 'Albania', ar: 'ألبانيا' }, code: 'AL' },
  { name: { fr: 'Algérie', en: 'Algeria', ar: 'الجزائر' }, code: 'DZ' },
  { name: { fr: 'Allemagne', en: 'Germany', ar: 'ألمانيا' }, code: 'DE' },
  { name: { fr: 'Andorre', en: 'Andorra', ar: 'أندورا' }, code: 'AD' },
  { name: { fr: 'Angola', en: 'Angola', ar: 'أنغولا' }, code: 'AO' },
  { name: { fr: 'Arabie Saoudite', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' }, code: 'SA' },
  { name: { fr: 'Argentine', en: 'Argentina', ar: 'الأرجنتين' }, code: 'AR' },
  { name: { fr: 'Australie', en: 'Australia', ar: 'أستراليا' }, code: 'AU' },
  { name: { fr: 'Autriche', en: 'Austria', ar: 'النمسا' }, code: 'AT' },
  { name: { fr: 'Belgique', en: 'Belgium', ar: 'بلجيكا' }, code: 'BE' },
  { name: { fr: 'Brésil', en: 'Brazil', ar: 'البرازيل' }, code: 'BR' },
  { name: { fr: 'Bulgarie', en: 'Bulgaria', ar: 'بلغاريا' }, code: 'BG' },
  { name: { fr: 'Cambodge', en: 'Cambodia', ar: 'كمبوديا' }, code: 'KH' },
  { name: { fr: 'Cameroun', en: 'Cameroon', ar: 'الكاميرون' }, code: 'CM' },
  { name: { fr: 'Canada', en: 'Canada', ar: 'كندا' }, code: 'CA' },
  { name: { fr: 'Chili', en: 'Chile', ar: 'تشيلي' }, code: 'CL' },
  { name: { fr: 'Chine', en: 'China', ar: 'الصين' }, code: 'CN' },
  { name: { fr: 'Colombie', en: 'Colombia', ar: 'كولومبيا' }, code: 'CO' },
  { name: { fr: 'Corée du Sud', en: 'South Korea', ar: 'كوريا الجنوبية' }, code: 'KR' },
  { name: { fr: 'Côte d\'Ivoire', en: 'Ivory Coast', ar: 'ساحل العاج' }, code: 'CI' },
  { name: { fr: 'Croatie', en: 'Croatia', ar: 'كرواتيا' }, code: 'HR' },
  { name: { fr: 'Danemark', en: 'Denmark', ar: 'الدنمارك' }, code: 'DK' },
  { name: { fr: 'Égypte', en: 'Egypt', ar: 'مصر' }, code: 'EG' },
  { name: { fr: 'Émirats Arabes Unis', en: 'United Arab Emirates', ar: 'الإمارات العربية المتحدة' }, code: 'AE' },
  { name: { fr: 'Équateur', en: 'Ecuador', ar: 'الإكوادور' }, code: 'EC' },
  { name: { fr: 'Espagne', en: 'Spain', ar: 'إسبانيا' }, code: 'ES' },
  { name: { fr: 'Estonie', en: 'Estonia', ar: 'إستونيا' }, code: 'EE' },
  { name: { fr: 'États-Unis', en: 'United States', ar: 'الولايات المتحدة' }, code: 'US' },
  { name: { fr: 'Finlande', en: 'Finland', ar: 'فنلندا' }, code: 'FI' },
  { name: { fr: 'France', en: 'France', ar: 'فرنسا' }, code: 'FR' },
  { name: { fr: 'Grèce', en: 'Greece', ar: 'اليونان' }, code: 'GR' },
  { name: { fr: 'Hongrie', en: 'Hungary', ar: 'المجر' }, code: 'HU' },
  { name: { fr: 'Inde', en: 'India', ar: 'الهند' }, code: 'IN' },
  { name: { fr: 'Indonésie', en: 'Indonesia', ar: 'إندونيسيا' }, code: 'ID' },
  { name: { fr: 'Irlande', en: 'Ireland', ar: 'أيرلندا' }, code: 'IE' },
  { name: { fr: 'Islande', en: 'Iceland', ar: 'آيسلندا' }, code: 'IS' },
  { name: { fr: 'Israël', en: 'Israel', ar: 'إسرائيل' }, code: 'IL' },
  { name: { fr: 'Italie', en: 'Italy', ar: 'إيطاليا' }, code: 'IT' },
  { name: { fr: 'Japon', en: 'Japan', ar: 'اليابان' }, code: 'JP' },
  { name: { fr: 'Lettonie', en: 'Latvia', ar: 'لاتفيا' }, code: 'LV' },
  { name: { fr: 'Liban', en: 'Lebanon', ar: 'لبنان' }, code: 'LB' },
  { name: { fr: 'Lituanie', en: 'Lithuania', ar: 'ليتوانيا' }, code: 'LT' },
  { name: { fr: 'Luxembourg', en: 'Luxembourg', ar: 'لوكسمبورغ' }, code: 'LU' },
  { name: { fr: 'Madagascar', en: 'Madagascar', ar: 'مدغشقر' }, code: 'MG' },
  { name: { fr: 'Malaisie', en: 'Malaysia', ar: 'ماليزيا' }, code: 'MY' },
  { name: { fr: 'Maroc', en: 'Morocco', ar: 'المغرب' }, code: 'MA' },
  { name: { fr: 'Mexique', en: 'Mexico', ar: 'المكسيك' }, code: 'MX' },
  { name: { fr: 'Monaco', en: 'Monaco', ar: 'موناكو' }, code: 'MC' },
  { name: { fr: 'Nigeria', en: 'Nigeria', ar: 'نيجيريا' }, code: 'NG' },
  { name: { fr: 'Norvège', en: 'Norway', ar: 'النرويج' }, code: 'NO' },
  { name: { fr: 'Nouvelle-Zélande', en: 'New Zealand', ar: 'نيوزيلندا' }, code: 'NZ' },
  { name: { fr: 'Pays-Bas', en: 'Netherlands', ar: 'هولندا' }, code: 'NL' },
  { name: { fr: 'Pérou', en: 'Peru', ar: 'بيرو' }, code: 'PE' },
  { name: { fr: 'Pologne', en: 'Poland', ar: 'بولندا' }, code: 'PL' },
  { name: { fr: 'Portugal', en: 'Portugal', ar: 'البرتغال' }, code: 'PT' },
  { name: { fr: 'Qatar', en: 'Qatar', ar: 'قطر' }, code: 'QA' },
  { name: { fr: 'République Tchèque', en: 'Czech Republic', ar: 'جمهورية التشيك' }, code: 'CZ' },
  { name: { fr: 'Roumanie', en: 'Romania', ar: 'رومانيا' }, code: 'RO' },
  { name: { fr: 'Royaume-Uni', en: 'United Kingdom', ar: 'المملكة المتحدة' }, code: 'GB' },
  { name: { fr: 'Russie', en: 'Russia', ar: 'روسيا' }, code: 'RU' },
  { name: { fr: 'Sénégal', en: 'Senegal', ar: 'السنغال' }, code: 'SN' },
  { name: { fr: 'Singapour', en: 'Singapore', ar: 'سنغافورة' }, code: 'SG' },
  { name: { fr: 'Slovaquie', en: 'Slovakia', ar: 'سلوفاكيا' }, code: 'SK' },
  { name: { fr: 'Slovénie', en: 'Slovenia', ar: 'سلوفينيا' }, code: 'SI' },
  { name: { fr: 'Suède', en: 'Sweden', ar: 'السويد' }, code: 'SE' },
  { name: { fr: 'Suisse', en: 'Switzerland', ar: 'سويسرا' }, code: 'CH' },
  { name: { fr: 'Thaïlande', en: 'Thailand', ar: 'تايلاند' }, code: 'TH' },
  { name: { fr: 'Tunisie', en: 'Tunisia', ar: 'تونس' }, code: 'TN' },
  { name: { fr: 'Turquie', en: 'Turkey', ar: 'تركيا' }, code: 'TR' },
  { name: { fr: 'Ukraine', en: 'Ukraine', ar: 'أوكرانيا' }, code: 'UA' },
  { name: { fr: 'Uruguay', en: 'Uruguay', ar: 'الأوروغواي' }, code: 'UY' },
  { name: { fr: 'Venezuela', en: 'Venezuela', ar: 'فنزويلا' }, code: 'VE' },
  { name: { fr: 'Viêt Nam', en: 'Vietnam', ar: 'فيتنام' }, code: 'VN' },
];
